name: Backup
version: 3.1
description: A full and simple backup plugin.
authors: [Meldanor, gamerx, lycano, Samuel98]
website: http://www.bukkitbackup.com/
dev-url: https://github.com/Samuel98/Backup
#dev-url: http://dev.bukkit.org/server-mods/backup/
main: com.bukkitbackup.full.BackupFull
commands:
  backup:
    description: Manually starts a backup of the server.
    usage: "Usage: /backup [args]"
    permission: backup.backup
  bu:
    description: Manually starts a backup of the server.
    usage: "Usage: /bu [args]"
    permission: backup.backup
permissions:
  backup.*:
    description: Permission to perform all commands.
    default: op
  backup.backup:
    description: Permission to perform a manual backup.
    default: op
  backup.notify:
    description: Permission to see when backups are started and completed.
    default: false
  backup.reload:
    description: Permission to reload configuration/strings.
    default: false
  backup.ver:
    description: Permission to display the version information.
    default: true
  backup.help:
    description: Permission to view help information.
    default: false
  backup.list:
    description: Permission to list the backups.
    default: false
  backup.toggle:
    description: Permission to enable/disable automatic backups.
    default: false
  backup.bypass:
    description: Players with this permission are not counted as online players.
    default: false
